[package]
name = "testing-things"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.6.0"

[[bench]]
name = "test_bench"
harness = false

[[bench]]
name = "another_bench"
harness = false