name: Test rust minimal setup
on:
  push:
    branches:
      - main

permissions:
    contents: write
    deployments: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: |
          rustup update && rustup default 
      - name: Run benchmark
        run: cargo bench | tee output.txt

      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: test benchmark
          # What benchmark tool the output.txt came from
          tool: 'cargo'
          # Where the output from the benchmark tool is stored
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          # Mention @rhysd in the commit comment
          alert-comment-cc-users: '@brycemines'

