name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/deploy-docs.yaml

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2

      - name: Copy benchmark results
        run: |
            git checkout bench dev/bench
            mv dev ./docs/_build/html

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html